import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Imaginer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko" placeholder="imaginer" className="dark">
      <body suppressHydrationWarning>{children}</body>
    </html>
  );
}
