import type { Metadata } from "next";
import "./globals.css";
import { PropsWithChildren } from "react";

export const metadata: Metadata = {
  title: "Imaginer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="ko" placeholder="imaginer" className="dark">
      <body suppressHydrationWarning>{children}</body>
    </html>
  );
}
