import type { Metadata } from "next";
import "./globals.css";
import { PropsWithChildren } from "react";
import { PromptProvider } from "@/components/provider/prompt-provider";

export const metadata: Metadata = {
  title: "Imaginer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="ko" placeholder="imaginer" className="dark">
      <body suppressHydrationWarning>
        <PromptProvider>{children}</PromptProvider>
      </body>
    </html>
  );
}
